version: "3"
services:
  app:
    image: docker-multi-staging
    ports:
      - "80:8080"
  jenkins:
    build:
      context: jenkins/
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "~/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"